### ISSUE TITLE
Reveal for hidden text

### ISSUE THREAD

**Issue by andyherbert** [16colo-rs/16c#42]
Tag artwork with hidden text (or autodetect) and strip away the colour information.

**Comment by bart-d** [comment]
I ran a test on the files with most hidden characters, a sample of about 500 files can be browsed here: https://16colo.rs/tmp/hidden/

Note that I did just pain converts assuming ansilove defaults, so wider content will not display properly in these tests. it looks like this reveal is more revealing towards 'lazy artists' using characters with the same fg/bg colors :D i've omitted spaces for the 'reveal' in any case, can't do that with blocks as that would defeat the purpose.

Some actual hidden content can be seen in these pieces:
https://16colo.rs/tmp/hidden/MA-BSUN.ANS.png
https://16colo.rs/tmp/hidden/fil-acer.ANS.png
https://16colo.rs/tmp/hidden/MT-BOMB2.ICE.png
https://16colo.rs/tmp/hidden/33-PROD2.ANS.png

**Comment by andyherbert** [comment]
Looks like Filth was a fan of hidden text. There is a slightly more sophisticated version of hidden text, which I'm not even sure that artists use, and that's using the high background colour with the low foreground colour, eg black on dark grey. With ice colours off it's hidden, but turning on ice colours reveals it.

**Comment by bart-d** [comment]
> Looks like Filth was a fan of hidden text. There is a slightly more sophisticated version of hidden text, which I'm not even sure that artists use, and that's using the high background colour with the low foreground colour, eg black on dark grey. With ice colours off it's hidden, but turning on ice colours reveals it.

interesting, I don't think i saw it before. i guess the only way to find out is to parse the entire arcive and find any occurences. quite sure there will be accidental occurences anyway just like for the regular hidden characters.

i currently don't see a way of getting rid of the "sloppy" or "accidental" hidden content. in any case not by number of characters as intentional hidden content can be very short too, like these examples, one of them looks like a 'copy protection' ;)

https://16colo.rs/tmp/hidden/DD-02.ANS.png
https://16colo.rs/tmp/hidden/DD-02.ANS.png

**Comment by bart-d** [comment]
item page now shows a 'reveal' button when the item contains at least 2 hidden characters (https://github.com/16colo-rs/16colo.rs/commit/143c3567515e9b44401d6bd426840cc9451930e3)

examples:
https://16colo.rs/pack2/legion06/FIL-MYTH.ANS
https://16colo.rs/pack/ice9705a/MT-BOMB2.ICE
https://16colo.rs/pack/mist1094/TE-IC1.ANS
https://16colo.rs/pack/ice-9502/TG-PC1.ICE
https://16colo.rs/pack/ice-9408/LS-DATA2.ICE
https://16colo.rs/pack/ice-9405/LS-TSBD.ICE

**Comment by andyherbert** [comment]
On https://16colo.rs/pack/mist0620/US-SOLOSCROLL.ANS I see some strange reveal behaviour:

<img width="42" alt="Screenshot 2020-06-17 at 17 20 51" src="https://user-images.githubusercontent.com/25620/84923511-343ee280-b0bf-11ea-90f7-f794d4366297.png">
<img width="42" alt="Screenshot 2020-06-17 at 17 21 05" src="https://user-images.githubusercontent.com/25620/84923537-3dc84a80-b0bf-11ea-8fd5-1c8c148617d0.png">

**Comment by bart-d** [comment]
![image](https://user-images.githubusercontent.com/6034441/84957289-2c049880-b0fb-11ea-8b82-793ff5c293fe.png)
![image](https://user-images.githubusercontent.com/6034441/84957318-3aeb4b00-b0fb-11ea-9ab2-38f099d439c5.png)

appears like i forgot to 'turn off' iCE colors after a [0m. this is fixed now, but it also means i'll have to reconvert all files with hidden text + iCE colors now because they might all be affected byt this bug. thanks!

**Comment by bart-d** [comment]
reopening to remind me to reconvert files with hidden content
